---
all:
  children:
    totems:
      hosts:
        metot:
          ansible_host: 192.168.8.136
          totem_artifact_arch: armv6l
          totemd_rust_target: arm-unknown-linux-musleabihf
          strfry_loader: ld-musl-armhf.so.1
        totem:
          ansible_host: 192.168.8.239
          totem_artifact_arch: armv6l
          totemd_rust_target: arm-unknown-linux-musleabihf
          strfry_loader: ld-musl-armhf.so.1
        motown:
          ansible_host: 192.168.8.196
          totem_artifact_arch: aarch64
          totemd_rust_target: aarch64-unknown-linux-musl
          strfry_loader: ld-musl-aarch64.so.1
      vars:
        ansible_user: totem
        ansible_become: true
        ansible_become_method: sudo
        ansible_ssh_common_args: -o StrictHostKeyChecking=accept-new
