---
all:
  children:
    totems:
      hosts:
        metot:
          ansible_host: 192.168.8.239
          totem_system_arch: armv7l
          totem_artifact_arch: armv6l
          totemd_rust_target: arm-unknown-linux-musleabihf
          strfry_loader: ld-musl-armhf.so.1
          totem_npub: npub1j0adney3t3tuvcaz6wv6eahpkhfrl8rwhry58n2u4njuxz0j04lsrudpf6
          totem_npub_hex: 93fad9e4915c57c663a2d399acf6e1b5d23f9c6eb8c943cd5cace5c309f27d7f
          totem_eink_driver: waveshare_2in13_v4
          totem_screen_enabled: true
          totem_screen_rotation: 180
          totem_ups_driver: pisugar2
          totem_spi_enabled: true
          totem_i2c_enabled: true
          totem_reboot_on_hardware_config_change: true
        totem:
          ansible_host: 192.168.8.136
          totem_system_arch: armv6l
          totem_artifact_arch: armv6l
          totemd_rust_target: arm-unknown-linux-musleabihf
          strfry_loader: ld-musl-armhf.so.1
          totem_npub: npub1eu0clm0nsxwavcsj07at3sy7v52tuwgw4qpeqsyxgkeqg7krc7ps77c20q
          totem_npub_hex: cf1f8fedf3819dd662127fbab8c09e6514be390ea80390408645b2047ac3c783
        motown:
          ansible_host: motown.local
          totem_system_arch: aarch64
          totem_artifact_arch: aarch64
          totemd_rust_target: aarch64-unknown-linux-musl
          strfry_loader: ld-musl-aarch64.so.1
          totem_npub: npub1rx7epldvux4d306aasw0n6y7wn9je0wa3yw4f8djpsw28g8zqzxsgg2g35
          totem_npub_hex: 19bd90fdace1aad8bf5dec1cf9e89e74cb2cbddd891d549db20c1ca3a0e2008d
      vars:
        ansible_user: totem
        ansible_become: true
        ansible_become_method: sudo
        ansible_ssh_common_args: -o StrictHostKeyChecking=accept-new
